import {decrypt,encrypt,money,parseExpense,randomCode} from './utils.js';
import {appendExpenses,refreshAccess} from './google.js';

const LINK_TTL=15*60*1000,PENDING_TTL=30*60*1000;

async function call(method,payload,env){const r=await fetch('https://api.telegram.org/bot'+env.TELEGRAM_BOT_TOKEN+'/'+method,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok||d.ok===false)throw new Error(d.description||'Telegram failed');return d.result}
export async function send(chatId,text,env,reply_markup){return call('sendMessage',{chat_id:chatId,text,...(reply_markup?{reply_markup}:{})},env)}
export async function setupWebhook(env){return call('setWebhook',{url:env.PUBLIC_BASE_URL.replace(/\/$/,'')+'/telegram/webhook',secret_token:env.TELEGRAM_WEBHOOK_SECRET,allowed_updates:['message','callback_query'],drop_pending_updates:true},env)}
async function userLink(id,env){const r=await env.DB.prepare('SELECT * FROM user_links WHERE telegram_user_id=?').bind(id).first();if(!r)return null;r.google_refresh_token=await decrypt(r.google_refresh_token,env.TOKEN_ENCRYPTION_KEY);return r}
export async function createLink(chatId,userId,env){const code=randomCode();await env.DB.prepare('INSERT INTO link_codes(code,telegram_user_id,chat_id,expires_at,used) VALUES(?,?,?,?,0)').bind(code,userId,chatId,Date.now()+LINK_TTL).run();const u=new URL(env.FRONTEND_URL);u.searchParams.set('link',code);return send(chatId,'Conecta tu Google una sola vez. Después todo gasto que confirmes aquí se guardará en tu hoja Mis gastos.',env,{inline_keyboard:[[{text:'Conectar Google',url:u.toString()}]]})}
export async function handleUpdate(update,env){if(update.callback_query)return callback(update.callback_query,env);const m=update.message;if(!m||m.chat?.type!=='private')return;const uid=String(m.from.id),chat=String(m.chat.id),text=String(m.text||m.caption||'').trim();const link=await userLink(uid,env);if(/^\/(start|link)\b/i.test(text))return link?send(chat,'Tu cuenta ya está conectada. Envíame algo como “450 en almuerzo en La Loma”.',env):createLink(chat,uid,env);if(!link)return createLink(chat,uid,env);if(m.photo||m.voice||m.audio)return send(chat,'Por ahora Telegram registra texto. Foto y audio ya funcionan en la web; los conectaremos a este mismo backend después.',env);if(!text)return send(chat,'Envíame un gasto escrito.',env);const p=await env.DB.prepare('SELECT * FROM pending WHERE telegram_user_id=?').bind(uid).first();if(p&&p.kind==='clarify'&&Number(p.expires_at)>Date.now()){const d=JSON.parse(p.payload);await env.DB.prepare('DELETE FROM pending WHERE telegram_user_id=?').bind(uid).run();return process(uid,chat,d.original+'\nAclaración: '+text,link,env)}return process(uid,chat,text,link,env)}
async function process(uid,chat,text,link,env){const r=parseExpense(text,{currency:link.currency||'NIO',timezone:link.timezone||'America/Managua'});if(r.question){await env.DB.prepare('INSERT INTO pending VALUES(?,?,?,?) ON CONFLICT(telegram_user_id) DO UPDATE SET kind=excluded.kind,payload=excluded.payload,expires_at=excluded.expires_at').bind(uid,'clarify',JSON.stringify({original:text}),Date.now()+PENDING_TTL).run();return send(chat,r.question,env)}await env.DB.prepare('INSERT INTO pending VALUES(?,?,?,?) ON CONFLICT(telegram_user_id) DO UPDATE SET kind=excluded.kind,payload=excluded.payload,expires_at=excluded.expires_at').bind(uid,'confirm',JSON.stringify({expenses:r.expenses}),Date.now()+PENDING_TTL).run();const lines=r.expenses.map(x=>(x.description+(x.merchant?' · '+x.merchant:'')+'\n'+x.category+' · '+money(x.amount,x.currency)+' · '+x.date));return send(chat,'Entendí:\n\n'+lines.join('\n\n')+'\n\n¿Lo guardo?',env,{inline_keyboard:[[{text:'Guardar',callback_data:'expense:save'},{text:'Corregir',callback_data:'expense:correct'}]]})}
async function callback(cb,env){await call('answerCallbackQuery',{callback_query_id:cb.id},env);const uid=String(cb.from.id),chat=String(cb.message?.chat?.id||cb.from.id),p=await env.DB.prepare('SELECT * FROM pending WHERE telegram_user_id=?').bind(uid).first();if(!p||p.kind!=='confirm'||Number(p.expires_at)<=Date.now())return send(chat,'Ese registro venció. Envíame el gasto otra vez.',env);if(cb.data==='expense:correct'){await env.DB.prepare('DELETE FROM pending WHERE telegram_user_id=?').bind(uid).run();return send(chat,'Escríbeme de nuevo el gasto con la corrección.',env)}if(cb.data!=='expense:save')return;const link=await userLink(uid,env);if(!link)return createLink(chat,uid,env);try{const access=await refreshAccess(link.google_refresh_token,env),payload=JSON.parse(p.payload);await appendExpenses(link.sheet_id,payload.expenses,access);await env.DB.prepare('DELETE FROM pending WHERE telegram_user_id=?').bind(uid).run();return send(chat,'Listo. Lo guardé en tu hoja Mis gastos.',env)}catch(e){console.error(e);return send(chat,'No pude escribir en Google Sheets. Usa /link para volver a conectar tu cuenta.',env)}}
export async function saveGoogleLink(link,refreshToken,sheetId,env){const enc=await encrypt(refreshToken,env.TOKEN_ENCRYPTION_KEY);await env.DB.prepare('INSERT INTO user_links(telegram_user_id,chat_id,google_refresh_token,sheet_id,currency,timezone,linked_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(telegram_user_id) DO UPDATE SET chat_id=excluded.chat_id,google_refresh_token=excluded.google_refresh_token,sheet_id=excluded.sheet_id,linked_at=excluded.linked_at').bind(link.telegram_user_id,link.chat_id,enc,sheetId,'NIO',env.DEFAULT_TIMEZONE||'America/Managua',Date.now()).run();await send(link.chat_id,'Listo. Telegram ya está conectado con tu hoja Mis gastos.',env)}
